/* eslint-disable */
/**
 * Generated by `npx convex codegen`.
 *
 * This is a stub file for local development. Run `npx convex dev` to
 * regenerate with full types from your Convex deployment.
 */
import type { AnyApi } from "convex/server";

/**
 * A type describing your app's public Convex API.
 *
 * This is a stub — run `npx convex dev` to generate full types.
 */
export const api: AnyApi = {} as any;
export const internal: AnyApi = {} as any;
