/* eslint-disable */
/**
 * Generated by `npx convex codegen`.
 *
 * This is a stub file for local development. Run `npx convex dev` to
 * regenerate with full types from your Convex deployment.
 */
import type { AnyDataModel } from "convex/server";

export type DataModel = AnyDataModel;
