/* eslint-disable */
/**
 * Generated by `npx convex codegen`.
 *
 * This is a stub file for local development. Run `npx convex dev` to
 * regenerate with full types from your Convex deployment.
 */
import {
  actionGeneric,
  httpActionGeneric,
  queryGeneric,
  mutationGeneric,
  internalActionGeneric,
  internalMutationGeneric,
  internalQueryGeneric,
} from "convex/server";
import type { DataModel } from "./dataModel.js";

export const query = queryGeneric as typeof queryGeneric;
export const mutation = mutationGeneric as typeof mutationGeneric;
export const action = actionGeneric as typeof actionGeneric;
export const httpAction = httpActionGeneric as typeof httpActionGeneric;
export const internalQuery = internalQueryGeneric as typeof internalQueryGeneric;
export const internalMutation = internalMutationGeneric as typeof internalMutationGeneric;
export const internalAction = internalActionGeneric as typeof internalActionGeneric;
