export interface ModelEntry {
  id: string;
  displayName: string;
  provider: string;
  contextWindow: number;
  maxOutputTokens?: number;
  costPerMInput: number;
  costPerMOutput: number;
  tier: 'free' | 'budget' | 'standard' | 'premium';
  capabilities: Set<'chat' | 'vision' | 'code' | 'long-context' | 'embedding' | 'structured-output'>;
  roles: Set<'agent' | 'observer' | 'guardrail' | 'embedding'>;
  active: boolean;
}

const MODEL_ID_ALIASES: Record<string, string> = {
  'openai/gpt-5-chat': 'openai/gpt-5-chat-latest',
  'openai/gpt-5.1-chat': 'openai/gpt-5.1-chat-latest',
  'openai/gpt-5.2-chat': 'openai/gpt-5.2-chat-latest',
  'openai/gpt-5.3-chat': 'openai/gpt-5.3-chat-latest',
};

export function normalizeModelId(id: string): string {
  return MODEL_ID_ALIASES[id] ?? id;
}

const MODELS: readonly ModelEntry[] = [
  // OpenAI
  {
    id: 'openai/gpt-5',
    displayName: 'GPT-5',
    provider: 'openai',
    contextWindow: 200000,
    maxOutputTokens: 32768,
    costPerMInput: 1.25,
    costPerMOutput: 10,
    tier: 'premium',
    capabilities: new Set(['chat', 'code', 'vision', 'structured-output']),
    roles: new Set(['agent']),
    active: true,
  },
  {
    id: 'openai/gpt-5-chat-latest',
    displayName: 'GPT-5 Chat',
    provider: 'openai',
    contextWindow: 200000,
    maxOutputTokens: 32768,
    costPerMInput: 1.25,
    costPerMOutput: 10,
    tier: 'premium',
    capabilities: new Set(['chat', 'vision', 'structured-output']),
    roles: new Set(['agent']),
    active: true,
  },
  {
    id: 'openai/gpt-5-codex',
    displayName: 'GPT-5 Codex',
    provider: 'openai',
    contextWindow: 200000,
    maxOutputTokens: 65536,
    costPerMInput: 2,
    costPerMOutput: 12,
    tier: 'premium',
    capabilities: new Set(['chat', 'code', 'structured-output']),
    roles: new Set(['agent']),
    active: true,
  },
  {
    id: 'openai/gpt-5-pro',
    displayName: 'GPT-5 Pro',
    provider: 'openai',
    contextWindow: 200000,
    maxOutputTokens: 65536,
    costPerMInput: 15,
    costPerMOutput: 60,
    tier: 'premium',
    capabilities: new Set(['chat', 'code', 'vision', 'structured-output']),
    roles: new Set(['agent']),
    active: true,
  },
  {
    id: 'openai/gpt-5-mini',
    displayName: 'GPT-5 Mini',
    provider: 'openai',
    contextWindow: 200000,
    maxOutputTokens: 32768,
    costPerMInput: 0.25,
    costPerMOutput: 2,
    tier: 'standard',
    capabilities: new Set(['chat', 'code', 'structured-output']),
    roles: new Set(['agent', 'observer']),
    active: true,
  },
  {
    id: 'openai/gpt-5-nano',
    displayName: 'GPT-5 Nano',
    provider: 'openai',
    contextWindow: 200000,
    maxOutputTokens: 16384,
    costPerMInput: 0.05,
    costPerMOutput: 0.4,
    tier: 'budget',
    capabilities: new Set(['chat', 'code', 'structured-output']),
    roles: new Set(['observer', 'guardrail']),
    active: true,
  },
  {
    id: 'openai/gpt-5.1',
    displayName: 'GPT-5.1',
    provider: 'openai',
    contextWindow: 200000,
    maxOutputTokens: 32768,
    costPerMInput: 2,
    costPerMOutput: 10,
    tier: 'premium',
    capabilities: new Set(['chat', 'code', 'vision', 'structured-output']),
    roles: new Set(['agent']),
    active: true,
  },
  {
    id: 'openai/gpt-5.1-chat-latest',
    displayName: 'GPT-5.1 Chat',
    provider: 'openai',
    contextWindow: 200000,
    maxOutputTokens: 32768,
    costPerMInput: 2,
    costPerMOutput: 10,
    tier: 'premium',
    capabilities: new Set(['chat', 'vision', 'structured-output']),
    roles: new Set(['agent']),
    active: true,
  },
  {
    id: 'openai/gpt-5.1-codex',
    displayName: 'GPT-5.1 Codex',
    provider: 'openai',
    contextWindow: 200000,
    maxOutputTokens: 65536,
    costPerMInput: 2.5,
    costPerMOutput: 12,
    tier: 'premium',
    capabilities: new Set(['chat', 'code', 'structured-output']),
    roles: new Set(['agent']),
    active: true,
  },
  {
    id: 'openai/gpt-5.1-codex-max',
    displayName: 'GPT-5.1 Codex Max',
    provider: 'openai',
    contextWindow: 200000,
    maxOutputTokens: 65536,
    costPerMInput: 3,
    costPerMOutput: 15,
    tier: 'premium',
    capabilities: new Set(['chat', 'code', 'structured-output']),
    roles: new Set(['agent']),
    active: true,
  },
  {
    id: 'openai/gpt-5.1-codex-mini',
    displayName: 'GPT-5.1 Codex Mini',
    provider: 'openai',
    contextWindow: 200000,
    maxOutputTokens: 32768,
    costPerMInput: 1,
    costPerMOutput: 5,
    tier: 'standard',
    capabilities: new Set(['chat', 'code', 'structured-output']),
    roles: new Set(['agent', 'observer']),
    active: true,
  },
  {
    id: 'openai/gpt-5.2',
    displayName: 'GPT-5.2',
    provider: 'openai',
    contextWindow: 200000,
    maxOutputTokens: 65536,
    costPerMInput: 3,
    costPerMOutput: 15,
    tier: 'premium',
    capabilities: new Set(['chat', 'code', 'vision', 'structured-output']),
    roles: new Set(['agent']),
    active: true,
  },
  {
    id: 'openai/gpt-5.2-chat-latest',
    displayName: 'GPT-5.2 Chat',
    provider: 'openai',
    contextWindow: 200000,
    maxOutputTokens: 65536,
    costPerMInput: 2,
    costPerMOutput: 12,
    tier: 'premium',
    capabilities: new Set(['chat', 'vision', 'structured-output']),
    roles: new Set(['agent']),
    active: true,
  },
  {
    id: 'openai/gpt-5.2-codex',
    displayName: 'GPT-5.2 Codex',
    provider: 'openai',
    contextWindow: 200000,
    maxOutputTokens: 65536,
    costPerMInput: 2.5,
    costPerMOutput: 12,
    tier: 'premium',
    capabilities: new Set(['chat', 'code', 'structured-output']),
    roles: new Set(['agent']),
    active: true,
  },
  {
    id: 'openai/gpt-5.2-pro',
    displayName: 'GPT-5.2 Pro',
    provider: 'openai',
    contextWindow: 200000,
    maxOutputTokens: 65536,
    costPerMInput: 15,
    costPerMOutput: 60,
    tier: 'premium',
    capabilities: new Set(['chat', 'code', 'vision', 'structured-output']),
    roles: new Set(['agent']),
    active: true,
  },
  {
    id: 'openai/gpt-5.3-chat-latest',
    displayName: 'GPT-5.3 Chat',
    provider: 'openai',
    contextWindow: 200000,
    maxOutputTokens: 65536,
    costPerMInput: 2.5,
    costPerMOutput: 12,
    tier: 'premium',
    capabilities: new Set(['chat', 'vision', 'structured-output']),
    roles: new Set(['agent']),
    active: true,
  },
  {
    id: 'openai/gpt-5.3-codex',
    displayName: 'GPT-5.3 Codex',
    provider: 'openai',
    contextWindow: 200000,
    maxOutputTokens: 65536,
    costPerMInput: 3,
    costPerMOutput: 15,
    tier: 'premium',
    capabilities: new Set(['chat', 'code', 'structured-output']),
    roles: new Set(['agent']),
    active: true,
  },
  {
    id: 'openai/gpt-5.4',
    displayName: 'GPT-5.4',
    provider: 'openai',
    contextWindow: 200000,
    maxOutputTokens: 65536,
    costPerMInput: 4,
    costPerMOutput: 18,
    tier: 'premium',
    capabilities: new Set(['chat', 'code', 'vision', 'structured-output']),
    roles: new Set(['agent']),
    active: true,
  },
  {
    id: 'openai/gpt-5.4-pro',
    displayName: 'GPT-5.4 Pro',
    provider: 'openai',
    contextWindow: 200000,
    maxOutputTokens: 65536,
    costPerMInput: 18,
    costPerMOutput: 72,
    tier: 'premium',
    capabilities: new Set(['chat', 'code', 'vision', 'structured-output']),
    roles: new Set(['agent']),
    active: true,
  },
  {
    id: 'openai/o3',
    displayName: 'O3',
    provider: 'openai',
    contextWindow: 200000,
    costPerMInput: 60,
    costPerMOutput: 60,
    tier: 'premium',
    capabilities: new Set(['code', 'long-context']),
    roles: new Set(['agent']),
    active: true,
  },
  {
    id: 'openai/o3-mini',
    displayName: 'O3 Mini',
    provider: 'openai',
    contextWindow: 200000,
    costPerMInput: 1.1,
    costPerMOutput: 4.4,
    tier: 'standard',
    capabilities: new Set(['code', 'long-context']),
    roles: new Set(['agent', 'observer']),
    active: true,
  },
  {
    id: 'openai/o4-mini',
    displayName: 'O4 Mini',
    provider: 'openai',
    contextWindow: 200000,
    costPerMInput: 1.50,
    costPerMOutput: 6,
    tier: 'standard',
    capabilities: new Set(['code', 'long-context']),
    roles: new Set(['agent']),
    active: true,
  },

  // Anthropic
  {
    id: 'anthropic/claude-opus-4-6',
    displayName: 'Claude Opus 4.6',
    provider: 'anthropic',
    contextWindow: 200000,
    maxOutputTokens: 8192,
    costPerMInput: 15,
    costPerMOutput: 75,
    tier: 'premium',
    capabilities: new Set(['chat', 'code', 'vision', 'long-context', 'structured-output']),
    roles: new Set(['agent']),
    active: true,
  },
  {
    id: 'anthropic/claude-sonnet-4-6',
    displayName: 'Claude Sonnet 4.6',
    provider: 'anthropic',
    contextWindow: 200000,
    maxOutputTokens: 8192,
    costPerMInput: 3,
    costPerMOutput: 15,
    tier: 'standard',
    capabilities: new Set(['chat', 'code', 'vision', 'structured-output']),
    roles: new Set(['agent']),
    active: true,
  },
  {
    id: 'anthropic/claude-haiku-4-5',
    displayName: 'Claude Haiku 4.5',
    provider: 'anthropic',
    contextWindow: 200000,
    maxOutputTokens: 8192,
    costPerMInput: 0.80,
    costPerMOutput: 4,
    tier: 'budget',
    capabilities: new Set(['chat', 'code', 'vision']),
    roles: new Set(['observer']),
    active: true,
  },

  // Google
  {
    id: 'google/gemini-3.1-pro-preview',
    displayName: 'Gemini 3.1 Pro (Preview)',
    provider: 'google',
    contextWindow: 1000000,
    maxOutputTokens: 8192,
    costPerMInput: 1.5,
    costPerMOutput: 6,
    tier: 'standard',
    capabilities: new Set(['chat', 'code', 'vision', 'long-context', 'structured-output']),
    roles: new Set(['agent', 'observer']),
    active: true,
  },
  {
    id: 'google/gemini-3-flash-preview',
    displayName: 'Gemini 3 Flash (Preview)',
    provider: 'google',
    contextWindow: 1000000,
    maxOutputTokens: 8192,
    costPerMInput: 0.10,
    costPerMOutput: 0.40,
    tier: 'budget',
    capabilities: new Set(['chat', 'code', 'vision', 'long-context']),
    roles: new Set(['agent', 'observer', 'guardrail']),
    active: true,
  },
  {
    id: 'google/gemini-3.1-flash-image-preview',
    displayName: 'Gemini 3.1 Flash Image (Preview)',
    provider: 'google',
    contextWindow: 1000000,
    maxOutputTokens: 8192,
    costPerMInput: 0.10,
    costPerMOutput: 0.40,
    tier: 'budget',
    capabilities: new Set(['chat', 'vision', 'long-context']),
    roles: new Set(['observer']),
    active: true,
  },
  {
    id: 'google/gemini-2.5-pro',
    displayName: 'Gemini 2.5 Pro',
    provider: 'google',
    contextWindow: 1000000,
    maxOutputTokens: 8192,
    costPerMInput: 1.25,
    costPerMOutput: 5,
    tier: 'standard',
    capabilities: new Set(['chat', 'code', 'vision', 'long-context', 'structured-output']),
    roles: new Set(['agent', 'observer']),
    active: true,
  },
  {
    id: 'google/gemini-2.5-flash',
    displayName: 'Gemini 2.5 Flash',
    provider: 'google',
    contextWindow: 1000000,
    maxOutputTokens: 8192,
    costPerMInput: 0.075,
    costPerMOutput: 0.30,
    tier: 'budget',
    capabilities: new Set(['chat', 'code', 'vision', 'long-context']),
    roles: new Set(['agent', 'observer', 'guardrail']),
    active: true,
  },
  {
    id: 'google/gemini-2.5-flash-lite',
    displayName: 'Gemini 2.5 Flash Lite',
    provider: 'google',
    contextWindow: 1000000,
    maxOutputTokens: 8192,
    costPerMInput: 0.015,
    costPerMOutput: 0.06,
    tier: 'free',
    capabilities: new Set(['chat', 'vision', 'long-context']),
    roles: new Set(['observer']),
    active: true,
  },
  {
    id: 'google/gemini-3.1-flash-lite-preview',
    displayName: 'Gemini 3.1 Flash Lite (Preview)',
    provider: 'google',
    contextWindow: 1000000,
    costPerMInput: 0.01,
    costPerMOutput: 0.04,
    tier: 'free',
    capabilities: new Set(['chat', 'vision']),
    roles: new Set(['observer']),
    active: true,
  },
  {
    id: 'google/gemini-embedding-001',
    displayName: 'Gemini Embedding 001',
    provider: 'google',
    contextWindow: 2048,
    costPerMInput: 0.01,
    costPerMOutput: 0,
    tier: 'free',
    capabilities: new Set(['embedding']),
    roles: new Set(['embedding']),
    active: true,
  },

  // Mistral
  {
    id: 'mistral/mistral-large-latest',
    displayName: 'Mistral Large',
    provider: 'mistral',
    contextWindow: 128000,
    maxOutputTokens: 4096,
    costPerMInput: 2,
    costPerMOutput: 6,
    tier: 'standard',
    capabilities: new Set(['chat', 'code', 'vision', 'structured-output']),
    roles: new Set(['agent']),
    active: true,
  },
  {
    id: 'mistral/mistral-small-latest',
    displayName: 'Mistral Small',
    provider: 'mistral',
    contextWindow: 128000,
    maxOutputTokens: 8192,
    costPerMInput: 0.20,
    costPerMOutput: 0.60,
    tier: 'budget',
    capabilities: new Set(['chat', 'code']),
    roles: new Set(['agent', 'observer']),
    active: true,
  },

  // DeepSeek
  {
    id: 'deepseek/deepseek-chat',
    displayName: 'DeepSeek Chat',
    provider: 'deepseek',
    contextWindow: 128000,
    costPerMInput: 0.14,
    costPerMOutput: 0.28,
    tier: 'budget',
    capabilities: new Set(['chat', 'code', 'long-context']),
    roles: new Set(['agent']),
    active: true,
  },
  {
    id: 'deepseek/deepseek-reasoner',
    displayName: 'DeepSeek Reasoner',
    provider: 'deepseek',
    contextWindow: 64000,
    costPerMInput: 0.55,
    costPerMOutput: 2.19,
    tier: 'standard',
    capabilities: new Set(['chat', 'code', 'long-context']),
    roles: new Set(['agent']),
    active: true,
  },

  // xAI
  {
    id: 'xai/grok-3',
    displayName: 'Grok 3',
    provider: 'xai',
    contextWindow: 1000000,
    costPerMInput: 2,
    costPerMOutput: 10,
    tier: 'standard',
    capabilities: new Set(['chat', 'code', 'vision', 'long-context']),
    roles: new Set(['agent']),
    active: true,
  },
  {
    id: 'xai/grok-3-mini',
    displayName: 'Grok 3 Mini',
    provider: 'xai',
    contextWindow: 1000000,
    costPerMInput: 0.30,
    costPerMOutput: 1.50,
    tier: 'budget',
    capabilities: new Set(['chat', 'code']),
    roles: new Set(['agent', 'observer']),
    active: true,
  },

  // OpenRouter (pass-through proxy)
  {
    id: 'openrouter/*',
    displayName: 'OpenRouter (Pass-through)',
    provider: 'openrouter',
    contextWindow: 200000,
    costPerMInput: 0,
    costPerMOutput: 0,
    tier: 'standard',
    capabilities: new Set(['chat', 'vision', 'code']),
    roles: new Set(['agent']),
    active: true,
  },

  // Cohere
  {
    id: 'cohere/command-r-plus',
    displayName: 'Command R+',
    provider: 'cohere',
    contextWindow: 128000,
    maxOutputTokens: 4096,
    costPerMInput: 2.50,
    costPerMOutput: 10,
    tier: 'standard',
    capabilities: new Set(['chat', 'code', 'long-context', 'structured-output']),
    roles: new Set(['agent']),
    active: true,
  },
  {
    id: 'cohere/command-r',
    displayName: 'Command R',
    provider: 'cohere',
    contextWindow: 128000,
    maxOutputTokens: 4096,
    costPerMInput: 0.50,
    costPerMOutput: 1.50,
    tier: 'budget',
    capabilities: new Set(['chat', 'code']),
    roles: new Set(['agent', 'observer']),
    active: true,
  },

  // MoonshotAI
  {
    id: 'moonshotai/kimi-k2.5',
    displayName: 'Kimi K2.5',
    provider: 'moonshotai',
    contextWindow: 128000,
    maxOutputTokens: 16384,
    costPerMInput: 0.12,
    costPerMOutput: 0.12,
    tier: 'budget',
    capabilities: new Set(['chat', 'code', 'long-context']),
    roles: new Set(['agent', 'observer']),
    active: true,
  },
] as const;

const MODEL_MAP = new Map(MODELS.map(m => [m.id, m]));

export function getModel(id: string): ModelEntry | undefined {
  return MODEL_MAP.get(normalizeModelId(id));
}

export function getModelsByProvider(provider: string): ModelEntry[] {
  return MODELS.filter(m => m.provider === provider);
}

export function getActiveModels(): ModelEntry[] {
  return MODELS.filter(m => m.active);
}

export function getContextLimit(modelId: string): number {
  const model = getModel(modelId);
  return model?.contextWindow ?? 100000;
}

/**
 * Resolve a model ID to a registry entry, with optional fallback chain.
 * Returns the requested model if found; otherwise walks `fallbacks` in order
 * and returns the first one present in the registry.
 * Falls back to `moonshotai/kimi-k2.5` (the daemon default) if nothing matches.
 */
export function resolveModel(id: string, fallbacks: string[] = []): ModelEntry {
  const direct = getModel(id);
  if (direct) return direct;

  for (const fb of fallbacks) {
    const entry = getModel(fb);
    if (entry) return entry;
  }

  // Last-resort daemon default — moonshotai/kimi-k2.5 is always present in MODELS above,
  // so this assertion is safe as long as the static MODELS array is not mutated at runtime.
  return MODEL_MAP.get('moonshotai/kimi-k2.5')!;
}
