/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ObservabilityRouteImport } from './routes/observability'
import { Route as FilesRouteImport } from './routes/files'
import { Route as CronRouteImport } from './routes/cron'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AgentRunRouteImport } from './routes/agent-run'
import { Route as IndexRouteImport } from './routes/index'

const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservabilityRoute = ObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const CronRoute = CronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRunRoute = AgentRunRouteImport.update({
  id: '/agent-run',
  path: '/agent-run',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-run': typeof AgentRunRoute
  '/agents': typeof AgentsRoute
  '/chat': typeof ChatRoute
  '/connections': typeof ConnectionsRoute
  '/cron': typeof CronRoute
  '/files': typeof FilesRoute
  '/observability': typeof ObservabilityRoute
  '/projects': typeof ProjectsRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/usage': typeof UsageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-run': typeof AgentRunRoute
  '/agents': typeof AgentsRoute
  '/chat': typeof ChatRoute
  '/connections': typeof ConnectionsRoute
  '/cron': typeof CronRoute
  '/files': typeof FilesRoute
  '/observability': typeof ObservabilityRoute
  '/projects': typeof ProjectsRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/usage': typeof UsageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-run': typeof AgentRunRoute
  '/agents': typeof AgentsRoute
  '/chat': typeof ChatRoute
  '/connections': typeof ConnectionsRoute
  '/cron': typeof CronRoute
  '/files': typeof FilesRoute
  '/observability': typeof ObservabilityRoute
  '/projects': typeof ProjectsRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/usage': typeof UsageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-run'
    | '/agents'
    | '/chat'
    | '/connections'
    | '/cron'
    | '/files'
    | '/observability'
    | '/projects'
    | '/sessions'
    | '/settings'
    | '/skills'
    | '/usage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-run'
    | '/agents'
    | '/chat'
    | '/connections'
    | '/cron'
    | '/files'
    | '/observability'
    | '/projects'
    | '/sessions'
    | '/settings'
    | '/skills'
    | '/usage'
  id:
    | '__root__'
    | '/'
    | '/agent-run'
    | '/agents'
    | '/chat'
    | '/connections'
    | '/cron'
    | '/files'
    | '/observability'
    | '/projects'
    | '/sessions'
    | '/settings'
    | '/skills'
    | '/usage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRunRoute: typeof AgentRunRoute
  AgentsRoute: typeof AgentsRoute
  ChatRoute: typeof ChatRoute
  ConnectionsRoute: typeof ConnectionsRoute
  CronRoute: typeof CronRoute
  FilesRoute: typeof FilesRoute
  ObservabilityRoute: typeof ObservabilityRoute
  ProjectsRoute: typeof ProjectsRoute
  SessionsRoute: typeof SessionsRoute
  SettingsRoute: typeof SettingsRoute
  SkillsRoute: typeof SkillsRoute
  UsageRoute: typeof UsageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observability': {
      id: '/observability'
      path: '/observability'
      fullPath: '/observability'
      preLoaderRoute: typeof ObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cron': {
      id: '/cron'
      path: '/cron'
      fullPath: '/cron'
      preLoaderRoute: typeof CronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-run': {
      id: '/agent-run'
      path: '/agent-run'
      fullPath: '/agent-run'
      preLoaderRoute: typeof AgentRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRunRoute: AgentRunRoute,
  AgentsRoute: AgentsRoute,
  ChatRoute: ChatRoute,
  ConnectionsRoute: ConnectionsRoute,
  CronRoute: CronRoute,
  FilesRoute: FilesRoute,
  ObservabilityRoute: ObservabilityRoute,
  ProjectsRoute: ProjectsRoute,
  SessionsRoute: SessionsRoute,
  SettingsRoute: SettingsRoute,
  SkillsRoute: SkillsRoute,
  UsageRoute: UsageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
