/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as SkillsMarketplaceRouteImport } from './routes/skills-marketplace'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ObservabilityRouteImport } from './routes/observability'
import { Route as FilesRouteImport } from './routes/files'
import { Route as CronRouteImport } from './routes/cron'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions.$sessionId'
import { Route as RunsRunIdRouteImport } from './routes/runs.$runId'
import { Route as AgentsAgentIdRouteImport } from './routes/agents.$agentId'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsMarketplaceRoute = SkillsMarketplaceRouteImport.update({
  id: '/skills-marketplace',
  path: '/skills-marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservabilityRoute = ObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const CronRoute = CronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => SessionsRoute,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/chat': typeof ChatRoute
  '/connections': typeof ConnectionsRoute
  '/cron': typeof CronRoute
  '/files': typeof FilesRoute
  '/observability': typeof ObservabilityRoute
  '/projects': typeof ProjectsRoute
  '/research': typeof ResearchRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/skills-marketplace': typeof SkillsMarketplaceRoute
  '/usage': typeof UsageRoute
  '/workflows': typeof WorkflowsRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/chat': typeof ChatRoute
  '/connections': typeof ConnectionsRoute
  '/cron': typeof CronRoute
  '/files': typeof FilesRoute
  '/observability': typeof ObservabilityRoute
  '/projects': typeof ProjectsRoute
  '/research': typeof ResearchRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/skills-marketplace': typeof SkillsMarketplaceRoute
  '/usage': typeof UsageRoute
  '/workflows': typeof WorkflowsRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/chat': typeof ChatRoute
  '/connections': typeof ConnectionsRoute
  '/cron': typeof CronRoute
  '/files': typeof FilesRoute
  '/observability': typeof ObservabilityRoute
  '/projects': typeof ProjectsRoute
  '/research': typeof ResearchRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/skills-marketplace': typeof SkillsMarketplaceRoute
  '/usage': typeof UsageRoute
  '/workflows': typeof WorkflowsRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/chat'
    | '/connections'
    | '/cron'
    | '/files'
    | '/observability'
    | '/projects'
    | '/research'
    | '/sessions'
    | '/settings'
    | '/skills'
    | '/skills-marketplace'
    | '/usage'
    | '/workflows'
    | '/agents/$agentId'
    | '/runs/$runId'
    | '/sessions/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/chat'
    | '/connections'
    | '/cron'
    | '/files'
    | '/observability'
    | '/projects'
    | '/research'
    | '/sessions'
    | '/settings'
    | '/skills'
    | '/skills-marketplace'
    | '/usage'
    | '/workflows'
    | '/agents/$agentId'
    | '/runs/$runId'
    | '/sessions/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/chat'
    | '/connections'
    | '/cron'
    | '/files'
    | '/observability'
    | '/projects'
    | '/research'
    | '/sessions'
    | '/settings'
    | '/skills'
    | '/skills-marketplace'
    | '/usage'
    | '/workflows'
    | '/agents/$agentId'
    | '/runs/$runId'
    | '/sessions/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRouteWithChildren
  ChatRoute: typeof ChatRoute
  ConnectionsRoute: typeof ConnectionsRoute
  CronRoute: typeof CronRoute
  FilesRoute: typeof FilesRoute
  ObservabilityRoute: typeof ObservabilityRoute
  ProjectsRoute: typeof ProjectsRoute
  ResearchRoute: typeof ResearchRoute
  SessionsRoute: typeof SessionsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SkillsRoute: typeof SkillsRoute
  SkillsMarketplaceRoute: typeof SkillsMarketplaceRoute
  UsageRoute: typeof UsageRoute
  WorkflowsRoute: typeof WorkflowsRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills-marketplace': {
      id: '/skills-marketplace'
      path: '/skills-marketplace'
      fullPath: '/skills-marketplace'
      preLoaderRoute: typeof SkillsMarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observability': {
      id: '/observability'
      path: '/observability'
      fullPath: '/observability'
      preLoaderRoute: typeof ObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cron': {
      id: '/cron'
      path: '/cron'
      fullPath: '/cron'
      preLoaderRoute: typeof CronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof AgentsRoute
    }
  }
}

interface AgentsRouteChildren {
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsAgentIdRoute: AgentsAgentIdRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface SessionsRouteChildren {
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
}

const SessionsRouteChildren: SessionsRouteChildren = {
  SessionsSessionIdRoute: SessionsSessionIdRoute,
}

const SessionsRouteWithChildren = SessionsRoute._addFileChildren(
  SessionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRouteWithChildren,
  ChatRoute: ChatRoute,
  ConnectionsRoute: ConnectionsRoute,
  CronRoute: CronRoute,
  FilesRoute: FilesRoute,
  ObservabilityRoute: ObservabilityRoute,
  ProjectsRoute: ProjectsRoute,
  ResearchRoute: ResearchRoute,
  SessionsRoute: SessionsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SkillsRoute: SkillsRoute,
  SkillsMarketplaceRoute: SkillsMarketplaceRoute,
  UsageRoute: UsageRoute,
  WorkflowsRoute: WorkflowsRoute,
  RunsRunIdRoute: RunsRunIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
