// This file is auto-generated by TanStack Router
// You should not edit this file manually

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexRoute } from "./routes/index";
import { Route as ChatRoute } from "./routes/chat";
import { Route as AgentsRoute } from "./routes/agents";
import { Route as SessionsRoute } from "./routes/sessions";
import { Route as FilesRoute } from "./routes/files";
import { Route as ProjectsRoute } from "./routes/projects";
import { Route as SkillsRoute } from "./routes/skills";
import { Route as CronRoute } from "./routes/cron";
import { Route as ConnectionsRoute } from "./routes/connections";
import { Route as SettingsRoute } from "./routes/settings";
import { Route as UsageRoute } from "./routes/usage";

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      preLoaderRoute: typeof IndexRoute;
      parentRoute: typeof rootRoute;
    };
    "/chat": {
      preLoaderRoute: typeof ChatRoute;
      parentRoute: typeof rootRoute;
    };
    "/agents": {
      preLoaderRoute: typeof AgentsRoute;
      parentRoute: typeof rootRoute;
    };
    "/sessions": {
      preLoaderRoute: typeof SessionsRoute;
      parentRoute: typeof rootRoute;
    };
    "/files": {
      preLoaderRoute: typeof FilesRoute;
      parentRoute: typeof rootRoute;
    };
    "/projects": {
      preLoaderRoute: typeof ProjectsRoute;
      parentRoute: typeof rootRoute;
    };
    "/skills": {
      preLoaderRoute: typeof SkillsRoute;
      parentRoute: typeof rootRoute;
    };
    "/cron": {
      preLoaderRoute: typeof CronRoute;
      parentRoute: typeof rootRoute;
    };
    "/connections": {
      preLoaderRoute: typeof ConnectionsRoute;
      parentRoute: typeof rootRoute;
    };
    "/settings": {
      preLoaderRoute: typeof SettingsRoute;
      parentRoute: typeof rootRoute;
    };
    "/usage": {
      preLoaderRoute: typeof UsageRoute;
      parentRoute: typeof rootRoute;
    };
  }
}

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  ChatRoute,
  AgentsRoute,
  SessionsRoute,
  FilesRoute,
  ProjectsRoute,
  SkillsRoute,
  CronRoute,
  ConnectionsRoute,
  SettingsRoute,
  UsageRoute,
]);
