import { defineConfig } from 'tsup';

export default defineConfig({
  entry: ['src/index.ts'],
  format: ['esm'],
  dts: true,
  splitting: false,
  sourcemap: true,
  clean: true,
  outDir: 'dist',
  target: 'node18',
  banner: {
    js: '#!/usr/bin/env node',
  },
  external: [
    'convex',
    'convex/browser',
    'commander',
    'fs-extra',
    'chalk',
    'gray-matter',
    '@agentforge-ai/runtime',
    '@agentforge-ai/core',
    '@mastra/core',
    '@mastra/core/agent',
    '@mastra/core/processors',
    '@mastra/core/llm',
    '@mastra/memory',
    '@mastra/convex',
    // Node builtins
    'node:path',
    'node:fs',
    'node:url',
    'node:child_process',
    'node:readline',
    'node:crypto',
    'path',
    'fs',
    'url',
    'child_process',
    'readline',
    'crypto',
    'events',
    'os',
    'util',
    'stream',
    'tty',
    'net',
    'http',
    'https',
  ],
  platform: 'node',
  publicDir: 'templates',
});
